version: "3.9"

services:
  cartera-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      #- ./cartera_inversiones.db:/app/cartera_inversiones.db
    environment:
      - PYTHONUNBUFFERED=1
